# Generated by Django 5.0.6 on 2024-07-27 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "contact")},
        ),
    ]
